### ISSUE TITLE
vk_api.exceptions.ApiError: [100] One of the parameters specified was missing or invalid: owner_id not integer

### ISSUE THREAD

**Issue by fitwist** [VadVergasov/vkparserbot#1]
Something is wrong with the token:
"vk_token": "[85-symbol-length-token]".

Token is created following this tutorial: https://www.youtube.com/watch?v=u1HvVYeCbgY

I've tried to add 'owner_id' after ampersand and write email or user ID, but it doesn't work. What should I do to complete the configuration?

**Comment by VadVergasov** [comment]
You can get "vk_token" on the page where the program ID is located. It is the 3rd field. For me, it's 71 symbol length

**Comment by VadVergasov** [comment]
No info for a long time, so I'll close it.
